# A simple list of key value replacements for parameter names
function = "func"
repeat = "_repeat"
end = "_end"
"path.mid" = "midi_path"
"pretty-print" = "pretty"
"upper-left-x" = "upper_left_x"
"upper-left-y" = "upper_left_y"
