[package]
name = "doc_scraper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

reqwest = {version = "0.11.18", features = ["blocking"]}
scraper = "0.17.1"
regex = "1.9.1"
serde_json = "1.0.104"
